version: '3.8'

services:
  frontend:
    build: .
    container_name: excel-manager-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-network
    # DEPENDENCIA DE BACKEND COMENTADA TEMPORALMENTE
    # depends_on:
    #   - api-backend
    environment:
      - NODE_ENV=production
    # NOTA: Frontend configurado para usar backend externo en http://10.90.0.213:5000/
    # No se requiere servicio backend local

  # BACKEND COMENTADO TEMPORALMENTE - Descomentar cuando esté disponible
  # api-backend:
  #   # Reemplaza con la imagen de tu API backend
  #   image: your-api-backend:latest
  #   container_name: excel-manager-api
  #   ports:
  #     - "5000:5000"
  #   restart: unless-stopped
  #   networks:
  #     - app-network
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=your-database-url
  #   # volumes:
  #   #   - ./api-data:/app/data

networks:
  app-network:
    driver: bridge

# volumes:
#   api-data:
#     driver: local 

# BACKEND EXTERNO CONFIGURADO
# El frontend está configurado para conectarse a: http://10.90.0.213:5000/
# Las rutas /api/ son proxy-pasadas a través de nginx al backend externo
# 
# Si necesitas volver a un backend local, descomenta lo siguiente:
# 
# services:
#   api-backend:
#     image: your-api-backend:latest
#     container_name: excel-manager-api
#     ports:
#       - "5000:5000"
#     restart: unless-stopped
#     networks:
#       - app-network
#     environment:
#       - NODE_ENV=production
#       - DATABASE_URL=your-database-url 